### ISSUE TITLE
[pomoxis] Reticulatus-pomoxis tracking issue

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/reticulatus#42]
Reticulatus ships with a particular version of `pomoxis` to provide a hacked version of the `subsample_bam` that runs most fast. This is a tracking issue to keep tabs on it.

* [ ] Make it work properly (recently experiments have shown it doesnt actually work which is not ideal)
* [ ] Add some randomness to the track-filling approach by keeping a list of N reads that start within the end of the emptiest track
* [ ] Raise an error if the coverage subsetting fails to yield coverage +/- some epsilon from the target
