### ISSUE TITLE
Snakemake enhancement tracking issue

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/reticulatus#46]
Just a place to track changes to `Snakemake`:

**Merged**
* [x] [Fix minor bug causing multiple inputs to be collapsed to the first](https://bitbucket.org/snakemake/snakemake/pull-requests/370/prevent-flattening-lists-inside-rule-input/diff)

**Upstream Review**
* [ ] [Move parsing of command prefix and suffix to command runtime, allowing prefix and suffix to contain variables to be filled](https://github.com/snakemake/snakemake/pull/138)

**Polishing**
* [ ] Real-time job benchmarking (currently duplicates a lot of benchmark.py)
* [ ] GPU benchmarking (currently duplicates a lot of benchmark.py)

**Todo**
* [ ] -
